### ISSUE TITLE
make a one passage thorugh FCN-16 architecture

### ISSUE THREAD

**Issue by sangeet259** [nexus-kgp/adseg#4]
just the forward passage, no training required as of now

It will take a mini-batch of image tensor say mbx3x240x320 and return tensor mbx8x240x320
Resources :

* https://arxiv.org/abs/1411.4038
* https://github.com/meetshah1995/pytorch-semseg
* https://github.com/wkentaro/pytorch-fcn

**Comment by dibyadas** [comment]
Merged #5
